module Enchere {    
	
	exception ProduitExistePas {string raison;}; 
	const double pas = 1.1;
	
	struct Utilisateur{
	 string id;
	 string nom;
	 string mdp;
	 string adresse; 
	};

    typedef sequence<Utilisateur> ListeUtilisateurs;
    
   struct Produit {
    string id;
	string nom;
	string categorie;
    string description;
	double prix_depart;/*Cet attribut plus le pas sera le prix en cours */
	string date_fin;
	Utilisateur vendeur;
    };
	
	struct Vente{
	string idVente;
	Produit produitVendu;
	Utilisateur acheteur;
	string debutVente;
	string finVente;
	};
	
	typedef sequence<Produit> ListeProduits;
	typedef sequence<Vente> ListeVentes;
	
	 interface Acheteur_Vendeur{
		attribute ListeProduits listeproduits;
		oneway void recevoirNotification (in string message);
    };
	
    interface SystemeEnchere{
    	attribute ListeProduits tousLesProduits;
    	attribute ListeUtilisateurs tousLesUtilisateurs;
    	attribute ListeVentes tousLesVentesEncours;
		
		ListeProduits consulterListeProduits();
		ListeProduits rechercherProduit(in string critere) raises (ProduitExistePas);

		/* attribut HashMap qui permet de stocker pour chaque produit la correspondance entre les acheteurs et les prix proposés*/
		
    	boolean demanderNotificationEnchereEnCours (in Utilisateur user, in Produit produit, in Acheteur_Vendeur acheteur_VendeurIOR);
    	boolean creerCompte(in string username, in string userpswd, in string userAdresse);
    	Utilisateur seConnecter(in string username, in string userpswd);
    	
    	Utilisateur getAcheteurProduit(in Produit produit);
    	
		void publierProduit(in Utilisateur vendeur, in string nomProduit, in string categorieProduit, in string descProduit, in double prixProduit,in string dateProduit, in SystemeEnchere ior);
		/* instanciation d'un objet GestionEnchere à la publication d'un nouveau produit*/
    	
		
		string proposerPrix(in double prix, in Utilisateur user, in Produit produit);
		/*Cette methode permettra d'enlever une vente terminée de la liste des ventes en cours */
		void supprimerVente(in Vente vente);
		void enleverVente(in string venteID);
    };

    interface Archivage{
    	void archiverVenteAchevee(in Vente venteAcheve);
    	void mettreAuxEnchere();
    	boolean archiverProduits(in ListeProduits listeproduits);
    	boolean archiverUtilisateurs(in ListeUtilisateurs listeUtilisateurs);
    	boolean archiverVenteEncours(in ListeVentes listeVentes);
    	boolean archiverVenteTerminees(in ListeVentes listeVentes);
    	ListeProduits chargerProduits();
    	ListeUtilisateurs chargerUtilisateurs();
    	ListeVentes chargerVentesEncours();
    	ListeVentes chargerVenteTerminees();
    	void statistiques();
    };

};