module Enchere {    
	
	exception ProduitExistePas {string raison;}; 
	const double pas = 1.1;
	
	struct Utilisateur{
	 string id;
	 string nom;
	 string mdp;
	 string adresse; 
	};

    typedef sequence<Utilisateur> ListeUtilisateurs;
    
   struct Produit {
    string id;
	string nom;
	string categorie;
    string description;
	double prix_depart;/*Cet attribut plus le pas sera le prix en cours */
	string date_fin;
	Utilisateur vendeur;
	double prixMaxPropse;
	
    };
	
	
	
	struct Vente{
	string idVente;
	Produit produitVendu;
	Utilisateur acheteur;
	//date debut de la vente
	string debutVente;
	//si la vente trouve un acheteur, ceci est la date où le produit est acheté
	string finVente;
	//date limite de terminaison de la vente precisé par le vendeur
	string dateAchevee;
	};
	
	typedef sequence<Produit> ListeProduits;
	typedef sequence<Vente> ListeVentes;
	
	 interface Acheteur_Vendeur{
		attribute string notification;
		oneway void recevoirNotification (in string message);
    };
	
	struct ClientUpdate{
	Acheteur_Vendeur ac;
	boolean updateUI;
	};
	
	typedef sequence<ClientUpdate> ListeClientUpdate;
	
	
    interface SystemeEnchere{
    	attribute ListeProduits tousLesProduits;
    	attribute ListeUtilisateurs tousLesUtilisateurs;
    	attribute ListeVentes tousLesVentesEncours;
		
		ListeProduits consulterListeProduits();
		ListeProduits rechercherProduit(in string critere) raises (ProduitExistePas);

		/* attribut HashMap qui permet de stocker pour chaque produit la correspondance entre les acheteurs et les prix proposés*/
		
    	boolean demanderNotificationEnchereEnCours (in Utilisateur user, in Produit produit, in Acheteur_Vendeur acheteur_VendeurIOR);
    	boolean creerCompte(in string username, in string userpswd, in string userAdresse);
    	Utilisateur seConnecter(in string username, in string userpswd);
    	
    	Utilisateur getAcheteurProduit(in Produit produit);
    	
		Produit publierProduit(in Utilisateur vendeur, in string nomProduit, in string categorieProduit, in string descProduit, in double prixProduit,in string dateProduit, in SystemeEnchere ior);
		/* instanciation d'un objet GestionEnchere à la publication d'un nouveau produit*/
    	
	   void doneUpdatingClient(in Acheteur_Vendeur ior);
		
		ListeClientUpdate getUIUpdateStatus();
		
		boolean addClient(in ClientUpdate client);
		
		string proposerPrix(in double prix, in Utilisateur user, in Produit produit);
		/*Cette methode permettra d'enlever une vente terminée de la liste des ventes en cours */
		void supprimerVente(in Vente vente);
		void enleverVente(in string venteID);
		string statistiques();
    };

    interface Archivage{
    	void archiverVenteAchevee(in Vente venteAcheve);
    	void mettreAuxEnchere();
    	boolean archiverProduits(in ListeProduits listeproduits);
    	boolean archiverUtilisateurs(in ListeUtilisateurs listeUtilisateurs);
    	boolean archiverVenteEncours(in ListeVentes listeVentes);
    	boolean archiverVenteTerminees(in ListeVentes listeVentes);
    	/*boolean archiverUserNotifications();
    	boolean archiverUserProduitPropositions();
    	private Map<String, List<Acheteur_Vendeur>> prod_UserNotifications = new HashMap<>();
		  private Map<String, Map<String, List<Double>>> histo_prod_User_Prix = new HashMap<>();*/
    	ListeProduits chargerProduits();
    	ListeUtilisateurs chargerUtilisateurs();
    	ListeVentes chargerVentesEncours();
    	ListeVentes chargerVenteTerminees();
    	
    	
    };

};