package Enchere;


/**
* Enchere/_ArchivageStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* jeudi 19 mars 2015 01 h 47 CET
*/

public class _ArchivageStub extends org.omg.CORBA.portable.ObjectImpl implements Enchere.Archivage
{

  public void archiverVenteAchevee (Enchere.Vente venteAcheve)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("archiverVenteAchevee", true);
                Enchere.VenteHelper.write ($out, venteAcheve);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                archiverVenteAchevee (venteAcheve        );
            } finally {
                _releaseReply ($in);
            }
  } // archiverVenteAchevee

  public void mettreAuxEnchere ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("mettreAuxEnchere", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                mettreAuxEnchere (        );
            } finally {
                _releaseReply ($in);
            }
  } // mettreAuxEnchere

  public boolean archiverProduits (Enchere.Produit[] listeproduits)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("archiverProduits", true);
                Enchere.ListeProduitsHelper.write ($out, listeproduits);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return archiverProduits (listeproduits        );
            } finally {
                _releaseReply ($in);
            }
  } // archiverProduits

  public boolean archiverUtilisateurs (Enchere.Utilisateur[] listeUtilisateurs)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("archiverUtilisateurs", true);
                Enchere.ListeUtilisateursHelper.write ($out, listeUtilisateurs);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return archiverUtilisateurs (listeUtilisateurs        );
            } finally {
                _releaseReply ($in);
            }
  } // archiverUtilisateurs

  public Enchere.Produit[] chargerProduits ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("chargerProduits", true);
                $in = _invoke ($out);
                Enchere.Produit $result[] = Enchere.ListeProduitsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return chargerProduits (        );
            } finally {
                _releaseReply ($in);
            }
  } // chargerProduits

  public Enchere.Utilisateur[] chargerUtilisateurs ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("chargerUtilisateurs", true);
                $in = _invoke ($out);
                Enchere.Utilisateur $result[] = Enchere.ListeUtilisateursHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return chargerUtilisateurs (        );
            } finally {
                _releaseReply ($in);
            }
  } // chargerUtilisateurs

  public void statistiques ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("statistiques", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                statistiques (        );
            } finally {
                _releaseReply ($in);
            }
  } // statistiques

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Enchere/Archivage:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ArchivageStub
