package Enchere;


/**
* Enchere/Acheteur_VendeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 00 h 55 CEST
*/

public interface Acheteur_VendeurOperations 
{
  String notification ();
  void notification (String newNotification);
  void recevoirNotification (String message);
} // interface Acheteur_VendeurOperations
