package Enchere;


/**
* Enchere/Acheteur_Vendeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 16 h 31 CEST
*/

public interface Acheteur_Vendeur extends Acheteur_VendeurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Acheteur_Vendeur
