package Enchere;


/**
* Enchere/Acheteur_VendeurHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 00 h 55 CEST
*/

abstract public class Acheteur_VendeurHelper
{
  private static String  _id = "IDL:Enchere/Acheteur_Vendeur:1.0";

  public static void insert (org.omg.CORBA.Any a, Enchere.Acheteur_Vendeur that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Enchere.Acheteur_Vendeur extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Enchere.Acheteur_VendeurHelper.id (), "Acheteur_Vendeur");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Enchere.Acheteur_Vendeur read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Acheteur_VendeurStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Enchere.Acheteur_Vendeur value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Enchere.Acheteur_Vendeur narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Enchere.Acheteur_Vendeur)
      return (Enchere.Acheteur_Vendeur)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Enchere._Acheteur_VendeurStub stub = new Enchere._Acheteur_VendeurStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Enchere.Acheteur_Vendeur unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Enchere.Acheteur_Vendeur)
      return (Enchere.Acheteur_Vendeur)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Enchere._Acheteur_VendeurStub stub = new Enchere._Acheteur_VendeurStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
