package Enchere;


/**
* Enchere/Acheteur_VendeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 18 mars 2015 00 h 52 CET
*/

public interface Acheteur_VendeurOperations 
{
  Enchere.Produit[] listeproduits ();
  void listeproduits (Enchere.Produit[] newListeproduits);
  void recevoirNotification (String message);
} // interface Acheteur_VendeurOperations
