package Enchere;


/**
* Enchere/Acheteur_Vendeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* lundi 23 mars 2015 14 h 40 CET
*/

public interface Acheteur_Vendeur extends Acheteur_VendeurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Acheteur_Vendeur
