package Enchere;


/**
* Enchere/ArchivagePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 18 mars 2015 00 h 52 CET
*/

public abstract class ArchivagePOA extends org.omg.PortableServer.Servant
 implements Enchere.ArchivageOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("archiverVenteAchevee", new java.lang.Integer (0));
    _methods.put ("mettreAuxEnchere", new java.lang.Integer (1));
    _methods.put ("archiverProduits", new java.lang.Integer (2));
    _methods.put ("archiverUtilisateurs", new java.lang.Integer (3));
    _methods.put ("chargerProduits", new java.lang.Integer (4));
    _methods.put ("chargerUtilisateurs", new java.lang.Integer (5));
    _methods.put ("statistiques", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Enchere/Archivage/archiverVenteAchevee
       {
         Enchere.Vente venteAcheve = Enchere.VenteHelper.read (in);
         this.archiverVenteAchevee (venteAcheve);
         out = $rh.createReply();
         break;
       }

       case 1:  // Enchere/Archivage/mettreAuxEnchere
       {
         this.mettreAuxEnchere ();
         out = $rh.createReply();
         break;
       }

       case 2:  // Enchere/Archivage/archiverProduits
       {
         Enchere.Produit listeproduits[] = Enchere.ListeProduitsHelper.read (in);
         boolean $result = false;
         $result = this.archiverProduits (listeproduits);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Enchere/Archivage/archiverUtilisateurs
       {
         Enchere.Utilisateur listeUtilisateurs[] = Enchere.ListeUtilisateursHelper.read (in);
         boolean $result = false;
         $result = this.archiverUtilisateurs (listeUtilisateurs);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // Enchere/Archivage/chargerProduits
       {
         Enchere.Produit $result[] = null;
         $result = this.chargerProduits ();
         out = $rh.createReply();
         Enchere.ListeProduitsHelper.write (out, $result);
         break;
       }

       case 5:  // Enchere/Archivage/chargerUtilisateurs
       {
         Enchere.Utilisateur $result[] = null;
         $result = this.chargerUtilisateurs ();
         out = $rh.createReply();
         Enchere.ListeUtilisateursHelper.write (out, $result);
         break;
       }

       case 6:  // Enchere/Archivage/statistiques
       {
         this.statistiques ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Enchere/Archivage:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Archivage _this() 
  {
    return ArchivageHelper.narrow(
    super._this_object());
  }

  public Archivage _this(org.omg.CORBA.ORB orb) 
  {
    return ArchivageHelper.narrow(
    super._this_object(orb));
  }


} // class ArchivagePOA
