package Enchere;


/**
* Enchere/ArchivageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* lundi 23 mars 2015 14 h 40 CET
*/

public interface ArchivageOperations 
{
  void archiverVenteAchevee (Enchere.Vente venteAcheve);
  void mettreAuxEnchere ();
  boolean archiverProduits (Enchere.Produit[] listeproduits);
  boolean archiverUtilisateurs (Enchere.Utilisateur[] listeUtilisateurs);
  boolean archiverVenteEncours (Enchere.Vente[] listeVentes);
  boolean archiverVenteTerminees (Enchere.Vente[] listeVentes);
  Enchere.Produit[] chargerProduits ();
  Enchere.Utilisateur[] chargerUtilisateurs ();
  Enchere.Vente[] chargerVentesEncours ();
  Enchere.Vente[] chargerVenteTerminees ();
  void statistiques ();
} // interface ArchivageOperations
