package Enchere;


/**
* Enchere/ArchivageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 16 h 31 CEST
*/

public interface ArchivageOperations 
{
  void archiverVenteAchevee (Enchere.Vente venteAcheve);
  void mettreAuxEnchere ();
  boolean archiverProduits (Enchere.Produit[] listeproduits);
  boolean archiverUtilisateurs (Enchere.Utilisateur[] listeUtilisateurs);
  boolean archiverVenteEncours (Enchere.Vente[] listeVentes);
  boolean archiverVenteTerminees (Enchere.Vente[] listeVentes);

  /*boolean archiverUserNotifications();
      	boolean archiverUserProduitPropositions();
      	private Map<String, List<Acheteur_Vendeur>> prod_UserNotifications = new HashMap<>();
  		  private Map<String, Map<String, List<Double>>> histo_prod_User_Prix = new HashMap<>();*/
  Enchere.Produit[] chargerProduits ();
  Enchere.Utilisateur[] chargerUtilisateurs ();
  Enchere.Vente[] chargerVentesEncours ();
  Enchere.Vente[] chargerVenteTerminees ();
} // interface ArchivageOperations
