package Enchere;

/**
* Enchere/ArchivageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 16 h 31 CEST
*/

public final class ArchivageHolder implements org.omg.CORBA.portable.Streamable
{
  public Enchere.Archivage value = null;

  public ArchivageHolder ()
  {
  }

  public ArchivageHolder (Enchere.Archivage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Enchere.ArchivageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Enchere.ArchivageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Enchere.ArchivageHelper.type ();
  }

}
