package Enchere;


/**
* Enchere/ClientUpdate.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 16 h 31 CEST
*/

public final class ClientUpdate implements org.omg.CORBA.portable.IDLEntity
{
  public Enchere.Acheteur_Vendeur ac = null;
  public boolean updateUI = false;

  public ClientUpdate ()
  {
  } // ctor

  public ClientUpdate (Enchere.Acheteur_Vendeur _ac, boolean _updateUI)
  {
    ac = _ac;
    updateUI = _updateUI;
  } // ctor

} // class ClientUpdate
