package Enchere;


/**
* Enchere/ClientUpdateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 16 h 31 CEST
*/

abstract public class ClientUpdateHelper
{
  private static String  _id = "IDL:Enchere/ClientUpdate:1.0";

  public static void insert (org.omg.CORBA.Any a, Enchere.ClientUpdate that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Enchere.ClientUpdate extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = Enchere.Acheteur_VendeurHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "ac",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[1] = new org.omg.CORBA.StructMember (
            "updateUI",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Enchere.ClientUpdateHelper.id (), "ClientUpdate", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Enchere.ClientUpdate read (org.omg.CORBA.portable.InputStream istream)
  {
    Enchere.ClientUpdate value = new Enchere.ClientUpdate ();
    value.ac = Enchere.Acheteur_VendeurHelper.read (istream);
    value.updateUI = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Enchere.ClientUpdate value)
  {
    Enchere.Acheteur_VendeurHelper.write (ostream, value.ac);
    ostream.write_boolean (value.updateUI);
  }

}
