package Enchere;


/**
* Enchere/ListeClientUpdateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 16 h 31 CEST
*/

public final class ListeClientUpdateHolder implements org.omg.CORBA.portable.Streamable
{
  public Enchere.ClientUpdate value[] = null;

  public ListeClientUpdateHolder ()
  {
  }

  public ListeClientUpdateHolder (Enchere.ClientUpdate[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Enchere.ListeClientUpdateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Enchere.ListeClientUpdateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Enchere.ListeClientUpdateHelper.type ();
  }

}
