package Enchere;


/**
* Enchere/ListeUtilisateursHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 00 h 55 CEST
*/

abstract public class ListeUtilisateursHelper
{
  private static String  _id = "IDL:Enchere/ListeUtilisateurs:1.0";

  public static void insert (org.omg.CORBA.Any a, Enchere.Utilisateur[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Enchere.Utilisateur[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Enchere.UtilisateurHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Enchere.ListeUtilisateursHelper.id (), "ListeUtilisateurs", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Enchere.Utilisateur[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Enchere.Utilisateur value[] = null;
    int _len0 = istream.read_long ();
    value = new Enchere.Utilisateur[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Enchere.UtilisateurHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Enchere.Utilisateur[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Enchere.UtilisateurHelper.write (ostream, value[_i0]);
  }

}
