package Enchere;


/**
* Enchere/pas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 00 h 55 CEST
*/

public interface pas
{
  public static final double value = (double)(1.1);
}
