package Enchere;


/**
* Enchere/pas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* jeudi 19 mars 2015 01 h 47 CET
*/

public interface pas
{
  public static final double value = (double)(1.1);
}
