package Enchere;


/**
* Enchere/pas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* lundi 23 mars 2015 14 h 40 CET
*/

public interface pas
{
  public static final double value = (double)(1.1);
}
