package Enchere;


/**
* Enchere/Produit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 00 h 55 CEST
*/

public final class Produit implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String nom = null;
  public String categorie = null;
  public String description = null;
  public double prix_depart = (double)0;

  /*Cet attribut plus le pas sera le prix en cours */
  public String date_fin = null;
  public Enchere.Utilisateur vendeur = null;
  public double prixMaxPropse = (double)0;

  public Produit ()
  {
  } // ctor

  public Produit (String _id, String _nom, String _categorie, String _description, double _prix_depart, String _date_fin, Enchere.Utilisateur _vendeur, double _prixMaxPropse)
  {
    id = _id;
    nom = _nom;
    categorie = _categorie;
    description = _description;
    prix_depart = _prix_depart;
    date_fin = _date_fin;
    vendeur = _vendeur;
    prixMaxPropse = _prixMaxPropse;
  } // ctor

} // class Produit
