package Enchere;

/**
* Enchere/ProduitExistePasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* lundi 23 mars 2015 14 h 40 CET
*/

public final class ProduitExistePasHolder implements org.omg.CORBA.portable.Streamable
{
  public Enchere.ProduitExistePas value = null;

  public ProduitExistePasHolder ()
  {
  }

  public ProduitExistePasHolder (Enchere.ProduitExistePas initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Enchere.ProduitExistePasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Enchere.ProduitExistePasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Enchere.ProduitExistePasHelper.type ();
  }

}
