package Enchere;


/**
* Enchere/SystemeEnchere.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* jeudi 19 mars 2015 01 h 47 CET
*/

public interface SystemeEnchere extends SystemeEnchereOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SystemeEnchere
