package Enchere;

/**
* Enchere/SystemeEnchereHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 00 h 55 CEST
*/

public final class SystemeEnchereHolder implements org.omg.CORBA.portable.Streamable
{
  public Enchere.SystemeEnchere value = null;

  public SystemeEnchereHolder ()
  {
  }

  public SystemeEnchereHolder (Enchere.SystemeEnchere initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Enchere.SystemeEnchereHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Enchere.SystemeEnchereHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Enchere.SystemeEnchereHelper.type ();
  }

}
