package Enchere;

/**
* Enchere/VenteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 18 mars 2015 00 h 52 CET
*/

public final class VenteHolder implements org.omg.CORBA.portable.Streamable
{
  public Enchere.Vente value = null;

  public VenteHolder ()
  {
  }

  public VenteHolder (Enchere.Vente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Enchere.VenteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Enchere.VenteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Enchere.VenteHelper.type ();
  }

}
