package Enchere;


/**
* Enchere/Vente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* mercredi 1 avril 2015 00 h 55 CEST
*/

public final class Vente implements org.omg.CORBA.portable.IDLEntity
{
  public String idVente = null;
  public Enchere.Produit produitVendu = null;
  public Enchere.Utilisateur acheteur = null;

  //date debut de la vente
  public String debutVente = null;

  //si la vente trouve un acheteur, ceci est la date où le produit est acheté
  public String finVente = null;

  //date limite de terminaison de la vente precisé par le vendeur
  public String dateAchevee = null;

  public Vente ()
  {
  } // ctor

  public Vente (String _idVente, Enchere.Produit _produitVendu, Enchere.Utilisateur _acheteur, String _debutVente, String _finVente, String _dateAchevee)
  {
    idVente = _idVente;
    produitVendu = _produitVendu;
    acheteur = _acheteur;
    debutVente = _debutVente;
    finVente = _finVente;
    dateAchevee = _dateAchevee;
  } // ctor

} // class Vente
