package Enchere;


/**
* Enchere/Vente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from encheresIDL.idl
* jeudi 19 mars 2015 01 h 47 CET
*/

public final class Vente implements org.omg.CORBA.portable.IDLEntity
{
  public String idVente = null;
  public Enchere.Produit produitVendu = null;
  public Enchere.Utilisateur acheteur = null;
  public String debutVente = null;
  public String finVente = null;

  public Vente ()
  {
  } // ctor

  public Vente (String _idVente, Enchere.Produit _produitVendu, Enchere.Utilisateur _acheteur, String _debutVente, String _finVente)
  {
    idVente = _idVente;
    produitVendu = _produitVendu;
    acheteur = _acheteur;
    debutVente = _debutVente;
    finVente = _finVente;
  } // ctor

} // class Vente
